nelmio_api_doc:
    documentation:
        info:
            title: Student Management
            description: Swagger API Documentation
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/student(?!/doc$) # Accepts routes under /api except /api/doc
